# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-02 21:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_delete_article'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('post_date', models.DateTimeField(auto_now=True)),
                ('body', models.TextField()),
                ('featured_image', models.FileField(upload_to=b'')),
            ],
        ),
    ]
