- hosts: local
  vars_files:
    - vars.yml
  gather_facts: false
  become_user: "{{ project_name }}"

  tasks:  
  - name: Mount Project in code directory.
    file: src=/vagrant/{{project_name}} dest={{project_root}}/code/{{project_name}} state=link
  - name: Upgrade the virtualenv.
    pip: requirements={{ project_root }}/code/{{ project_name }}/requirements.txt virtualenv={{ project_root }}/env/
    become: yes
    become_user: '{{project_name}}'
  - name: Configure redis.
    copy: src=/vagrant/deployment/files/conf/redis.conf dest=/etc/redis/redis.conf
    become: yes
    become_user: root
    notify:
      - restart redis cache
  handlers:
  - name: restart apache
    service: name=apache2 state=restarted
    become: yes
    become_user: root

  - name: reload apache
    service: name=apache2 state=reloaded
    become: yes
    become_user: root

  - name: restart redis cache
    service: name=redis-server state=restarted
    become: yes
    become_user: root