- hosts: local
  vars_files:
    - vars.yml
  gather_facts: false
  become_user: "{{ project_name }}"

  tasks:  
  - name: Mount Project in code directory.
    file: src=/vagrant/{{project_name}} dest={{project_root}}/code/{{project_name}} state=link
  - name: Upgrade the virtualenv.
    pip: requirements={{ project_root }}/code/{{ project_name }}/requirements.txt virtualenv={{ project_root }}/env/
  - name: Configure redis.
    copy: src=/vagrant/deployment/files/conf/redis.conf dest=/etc/redis/redis.conf
    become_user: root
    notify:
      - restart redis cache
  - name: Migrate Django Database
    django_manage: command=migrate app_path={{ project_root }}/code/{{ project_name }} virtualenv={{ project_root }}/env/
  handlers:
    - include: handlers.yml
